twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic   : /input_joy/cmd_vel
        timeout : 0.5
        priority: 99
      keyboard: 
        topic   : /key_vel
        timeout : 0.5
        priority: 90
      navigation: 
        topic   : /cmd_vel_nav
        timeout : 0.5
        priority: 80
      collision_monitor: 
        topic   : /safe_cmd_vel
        timeout : 0.5
        priority: 95
